context:
  name: certbot-dns-digitalocean
  version: "5.3.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: f5c6a71941c13728ad1f404a7359c77f0c0daf22a597d1234590ad6b9014a1e2

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - acme >=${{ version }}
    - certbot >=${{ version }}
    - python-digitalocean >=1.15.0

tests:
  - python:
      imports:
        - certbot_dns_digitalocean
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://certbot.eff.org
  summary: DigitalOcean DNS Authenticator plugin for Certbot
  license: Apache-2.0
  license_file: LICENSE.txt
  documentation: https://certbot.eff.org
  repository: https://github.com/certbot/certbot

extra:
  recipe-maintainers:
    - pavelzw
